name: pull request into brunches
on: [pull_request]
jobs:
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go test ./test/unit/postgres 
      - run: go test ./test/unit/service 

      - uses: golangci/golangci-lint-action@v3

      - run: go build -v -o ./bin/main ./cmd/main.go
