name: pull request into brunches
on: [pull_request]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 150403

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go test ./test/integration
      - run: go test ./test/unit/postgres 
      - run: go test ./test/unit/service 

      - uses: golangci/golangci-lint-action@v3

      - run: go build -v -o ./bin/main ./cmd/main.go
