name: pull request into brunches
on: [pull_request]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: innotaxi_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go test ./test/unit/postgres 
      - run: go test ./test/unit/service 
      - run: psql -h postgres -d innotaxi_test -U postgres -c 'SELECT 1;'
      - run: go test ./test/integration

      - uses: golangci/golangci-lint-action@v3

      - run: go build -v -o ./bin/main ./cmd/main.go
